# Generated by Django 5.0 on 2023-12-21 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_employerprofile_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employerprofile',
            name='about',
        ),
        migrations.RemoveField(
            model_name='employerprofile',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='employerprofile',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='employerprofile',
            name='photo',
        ),
    ]
