# Generated by Django 5.0 on 2023-12-19 17:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('company_name', models.CharField(max_length=255)),
                ('about', models.TextField()),
                ('photo', models.ImageField(blank=True, upload_to='users/%Y/%m/%d/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('work_name', models.CharField(max_length=100)),
                ('about', models.TextField()),
                ('photo', models.ImageField(blank=True, upload_to='users/%Y/%m/%d/')),
                ('telephone', models.IntegerField()),
                ('city', models.CharField(max_length=100)),
                ('citizenship', models.CharField(choices=0, max_length=100)),
                ('salary', models.IntegerField()),
                ('gender', models.CharField(choices=[('M', 'Man'), ('W', 'Woman')], max_length=20)),
                ('date_of_birth', models.DateField()),
                ('experience', models.BooleanField()),
                ('created', models.DateField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resumes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('about', models.CharField(max_length=255)),
                ('responsibilities', models.CharField(max_length=255)),
                ('requirements', models.CharField(max_length=255)),
                ('conditions', models.CharField(max_length=255)),
                ('publish', models.DateField(auto_now=True)),
                ('active', models.BooleanField(default=False)),
                ('location', models.CharField(max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vacancies', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-publish'],
                'indexes': [models.Index(fields=['-publish'], name='service_vac_publish_b6c97c_idx')],
            },
        ),
    ]
