# Generated by Django 5.0 on 2023-12-20 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EmployerProfile',
        ),
    ]
