# Generated by Django 5.0 on 2023-12-20 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_delete_employerprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='citizenship',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='resume',
            name='experience',
            field=models.TextField(),
        ),
    ]
