# Generated by Django 5.0 on 2023-12-21 10:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0003_alter_resume_citizenship_alter_resume_experience'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resume',
            name='about',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='citizenship',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='city',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='date_of_birth',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='experience',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='salary',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='telephone',
        ),
        migrations.RemoveField(
            model_name='vacancy',
            name='about',
        ),
        migrations.RemoveField(
            model_name='vacancy',
            name='active',
        ),
        migrations.RemoveField(
            model_name='vacancy',
            name='conditions',
        ),
        migrations.RemoveField(
            model_name='vacancy',
            name='location',
        ),
        migrations.RemoveField(
            model_name='vacancy',
            name='requirements',
        ),
        migrations.RemoveField(
            model_name='vacancy',
            name='responsibilities',
        ),
        migrations.AddField(
            model_name='vacancy',
            name='responses',
            field=models.ManyToManyField(blank=True, related_name='responses', to=settings.AUTH_USER_MODEL),
        ),
    ]
