# Generated by Django 5.0 on 2023-12-24 08:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0005_vacancy_active'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancy',
            name='responses',
            field=models.ManyToManyField(blank=True, related_name='responses', to='service.resume'),
        ),
        migrations.AddIndex(
            model_name='vacancy',
            index=models.Index(fields=['name'], name='service_vac_name_8b93ed_idx'),
        ),
    ]
