# Generated by Django 5.0 on 2023-12-24 14:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0008_remove_vacancy_responses_alter_resume_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='user',
        ),
        migrations.AddField(
            model_name='application',
            name='resume',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='service.resume'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
